builds:
  - env:
      # goreleaser does not work with CGO
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.Date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - arm
    binary: "usr/local/kobomail/kobomail"
archives:
  - format: tar.gz
    name_template: "KoboRoot"
    rlcp: true
    files:
      - etc/*
      - usr/*
release:
  github:
    owner: bjw-s
    name: KoboMail
changelog:
  skip: false
  sort: asc
