---
name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tag information
        run: git fetch --force --tags

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
          cache: true

      - name: Run GoReleaser
        # Create a release when a tag is pushed
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
